name: SpecialZone
main: top.seatide.SpecialZone.Main
version: "1.0.0"
api-version: 1.16
authors: [ Subilan, Constant137 ]
commands:
  specialzone:
    aliases: ['sz']
    permission: specialzone.command
    description: SpecialZone main command
    usage: /specialzone <...>
permissions:
  specialzone.command:
    default: op
  specialzone.exception:
    default: op
  specialzone.select:
    default: op
