name: SpecialZone
main: org.sotap.SpecialZone.SpecialZone
version: "1.0.0"
api-version: 1.16
authors: [Subilan, Constant137]
commands:
  specialzone:
    permission: specialzone.command
    description: SpecialZone main command
    usage: /specialzone <...>
permissions:
  specialzone.command:
    default: op
